DEFAULT_WINDOW_SIZE = 9
DEFAULT_WITH_SLIDING_WINDOW = True
DEFAULT_PARTITIONS_AMT = 30
DEFAULT_SS_PREDICTOR_THRESHOLD = 0.65
DEFAULT_TRAIN_DATA_PCT = 0.7
DEFAULT_VALID_DATA_PCT = 0.1
DEFAULT_EPOCHS = 5
DEFAULT_BATCH_SIZE = 20
